version: 2

defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk

  working_directory: ~/repo

  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb


jobs:
  build:
    <<: *defaults
    environment:
      SPURWING_KEY: ${SPURWING_KEY}
      SPURWING_PID: $SPURWING_PID}      
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      - persist_to_workspace:
          root: ~/repo
          paths: .
 
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run Tests
          command: gradle run test
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build